# Generated by Django 5.0.14 on 2025-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', '대기 중'), ('CLONING_SUCCESS', '복제 성공'), ('INFER_SUCCESS', 'Infer 성공'), ('CPPLINT_SUCCESS', 'Cpplint 성공'), ('LIZARD_SUCCESS', 'Lizard 성공'), ('CLANG_SUCCESS', 'Clang/Build 성공'), ('PREPROCESSING', '전처리 중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
