# Generated by Django 5.0.14 on 2025-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='clang_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='cpplint_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='current_step',
            field=models.CharField(choices=[('NONE', '시작 전'), ('CLONING', 'GIT Clone'), ('CLANG', 'Clang Build'), ('INFER', 'Infer 분석'), ('CPPLINT', 'Cpplint 분석'), ('LIZARD', 'Lizard 분석'), ('PREPROCESSING', '전처리')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='infer_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='lizard_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('RUNNING', '실행 중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20),
        ),
    ]
